Repository Azure/azure-functions-openapi-extension, pull requests merged in 2021-10, with the labels that each got.

#250 Add integration testing for String Object Type (#143)
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Post_ApplicationJson_String_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Post_ApplicationJson_String_HttpTrigger.cs
Labels: enhancement, oca-pr

#243 Feature/#139 OpenAPI query string/path parameter examples
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiParameterAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/OpenApiParameterAttributeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/OpenApiExampleFactory.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/OpenApiExampleResolver.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_Query_ParameterExamples_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_Query_TextPlain_String_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/BooleanParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/ByteArrayParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/DateTimeOffsetParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/DateTimeParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/DoubleParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/GuidParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/Int16ParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/Int32ParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/Int64ParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/SingleParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/StringParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/Uint16ParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/Uint32ParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Examples/Uint64ParameterExample.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_Query_ParameterExamples_HttpTrigger.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_Query_TextPlain_String_HttpTrigger.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeBooleanParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeByteArrayParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeDateTimeOffsetParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeDateTimeParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeDoubleParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeGuidParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeInt16ParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeInt32ParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeInt64ParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeSingleParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeStringParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeUint16ParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeUint32ParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeUint64ParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Abstractions/IExampleTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Abstractions/OpenApiExampleTests.cs
Labels: enhancement, v0.9.0, oca-pr, oca-issue

#253 HTTP/HTTPS in Swagger UI + oauth2+redirect.html
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Document.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/HttpRequestDataObjectExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/DocumentTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/DefaultOpenApiConfigurationOptionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/EnumExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/HttpRequestDataObjectExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/SwaggerUITests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/DocumentTests.cs
Labels: bug, enhancement, v0.9.0, hacktoberfest

#246 Fix "could not resolve reference error" #160
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/DummyListModel.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/DictionaryObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ListObjectTypeVisitor.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_ApplicationJson_DictionaryObject_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/DictionaryObjectModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/DictionaryObjectTypeVisitorTests.cs
Labels: bug, v0.9.0, oca-pr, oca-issue

#255 Additional authentication mechanism for Swagger UI and OpenAPI doc
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/Configurations/OpenApiHttpTriggerAuthorization.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Extensions/OpenApiHostBuilderExtensions.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Extensions/OpenApiHttpRequestDataExtensions.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Functions/OpenApiTriggerFunction.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/HttpRequestObject.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IHttpRequestDataObject.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiHttpTriggerAuthorization.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiHttpTriggerAuthorization.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiAuthorizationResult.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/OpenApiHttpTriggerContextExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/HttpRequestObject.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/IOpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctions.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/Extensions/HttpRequestDataExtensionsTests.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/Fakes/FakeHttpRequestData.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/Fakes/FakeOpenApiHttpTriggerAuthorization.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/HttpRequestObjectTests.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/DefaultOpenApiHttpTriggerAuthorizationTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/OpenApiHttpTriggerContextExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/Fakes/FakeOpenApiHttpTriggerAuthorization.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/HttpRequestObjectTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
Labels: enhancement, v0.9.0

#252 Add integration testing for jObject Type
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_ApplicationJson_JObject_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_ApplicationJson_JObject_HttpTrigger.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/JObjectModel.cs
Labels: oca-pr, hacktoberfest

#256 Update docs for 0.9.0-preview
  docs/openapi-core.md
  docs/openapi-in-proc.md
  docs/openapi-out-of-proc.md
  docs/openapi.md
Labels: documentation, v0.9.0
