Repository Azure/azure-functions-openapi-extension, pull requests merged in 2021-04, with the labels that each got.

#81 Update RouteConstraintFilter with Tests
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/RouteConstraintFilter.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/DocumentHelper.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/RouteConstraintFilterTests.cs
Labels: enhancement, v0.6.0

#82 Fix Array of Array issue, including Dictionary
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/OpenApiSchemaExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/DictionaryObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ListObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/RecursiveObjectTypeVisitor.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
Labels: bug, v0.6.0

#80 Update DocumentHelper to use GetOpenApiReferenceId for acceptor keys
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/DocumentHelper.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeFunctions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeListModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeOtherClassModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeStringModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/DocumentHelperTests.cs
Labels: bug, v0.6.0

#91 Add OpenAPI spec version to config options
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/Configurations/OpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/IOpenApiConfigurationOptions.cs
  templates/OpenApiEndpoints/OpenApiHttpTrigger.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/DefaultOpenApiConfigurationOptionsTests.cs
Labels: enhancement, v0.7.0

#90 Dynamic OpenAPI document injection
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V1Proxy/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V1Proxy.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V2IoC/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V2IoC.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V2Static/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V2Static.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3IoC/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3IoC.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/local.settings.json
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/SwaggerUIExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/ISwaggerUI.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Configurations/OpenApiAuthLevelSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/HttpBindingMetadata.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/IOpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Microsoft.Azure.WebJobs.Extensions.OpenApi.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctionProvider.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiWebJobsStartup.cs
  templates/OpenApiEndpoints/OpenApiHttpTrigger.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/SwaggerUIExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiTriggerFunctionProviderTests.cs
Labels: enhancement, v0.7.0

#93 Update custom response header collection
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/DummyHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/ResponseHeaders/DummyResponseHeader.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiResponseWithBodyAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiResponseWithoutBodyAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/OpenApiResponseWithBodyAttributeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/OpenApiResponseWithoutBodyAttributeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/IOpenApiCustomResponseHeader.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeFunctions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeResponseHeader.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Attributes/OpenApiResponseWithBodyAttributeTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Attributes/OpenApiResponseWithoutBodyAttributeTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/OpenApiResponseWithBodyAttributeExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/OpenApiResponseWithoutBodyAttributeExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/TypeExtensionsTests.cs
Labels: enhancement, v0.7.0

#95 Example for request/response payload
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/Category.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/DummyStringModel.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/Examples/CategoryExample.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/Examples/DummyStringModelExample.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/DummyHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/Examples/DummyListModelExample.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiExample.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/OpenApiExample.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiExampleAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiPayloadAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Document.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/EnumExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/OpenApiPayloadAttributeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/OpenApiExampleResolver.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ObjectTypeVisitor.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests.Fakes/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests.Fakes.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Abstractions/IExampleTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Attributes/OpenApiExampleAttributeTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Attributes/OpenApiRequestBodyAttributeTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Attributes/OpenApiResponseWithBodyAttributeTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/EnumExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/OpenApiPayloadAttributeExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Resolvers/OpenApiExampleResolverTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests.csproj
Labels: enhancement, v0.8.0

#100 Hotfix: OpenAPI Methods
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V1Proxy/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V1Proxy.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V2IoC/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V2IoC.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V2Static/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V2Static.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3IoC/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3IoC.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/DependencyManifest.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/IOpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctionProvider.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
Labels: bug, resolved, v0.7.1

#104 Fix custom hostname for better discoverability
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/Configurations/OpenApiConfigurationOptions.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/local.settings.json
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings/AppSettingsBase.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings/Extensions/AppSettingsExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings/Extensions/ConfigurationBinderExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings/Resolvers/ConfigurationResolver.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/ProjectInfo.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiAppSettingsBase.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Document.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/HostJsonResolver.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiWebJobsStartup.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests.Fakes/FakeProductSettings.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests.Fakes/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests.Fakes.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests/AppSettingsBaseTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests/Extensions/ConfigurationBinderExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests/Resolvers/ConfigurationResolverTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/DefaultOpenApiConfigurationOptionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/DocumentTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/Configurations/OpenApiSettingsTests.cs
Labels: enhancement, v0.8.0

#111 Fix OpenApiConfigurationResolver
  .vscode/settings.json
  .vscode/tasks.json
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3IoC/Configurations/AppSettings.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3IoC/DefaultHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3IoC/StartUp.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3IoC/local.settings.json
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/OpenApiConfigurationResolver.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Resolvers/OpenApiConfigurationResolverTests.cs
Labels: bug, v0.7.2
