Repository Azure/azure-functions-openapi-extension, pull requests merged in 2021-09, with the labels that each got.

#208 fix Nullable DateTime type to display as date format in specification
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/NullableObjectTypeVisitor.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_ApplicationJson_DataType_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_ApplicationJson_DataType_HttpTrigger.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/DataTypeClass.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/NullableObjectTypeVisitorTests.cs
Labels: oca-pr, oca-issue

#224 Add ByteType Support
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ByteArrayTypeVisotor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/TypeVisitor.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Post_ApplicationJson_ByteArray_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/ByteArrayObjectModel.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Post_ApplicationJson_ByteArray_HttpTrigger.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/ByteArrayTypeVisitorTests.cs
Labels: oca-pr

#230 Update ListObjectTypeVisitor to include HashSet<T>
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/DummyListModel.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/Examples/DummyListModelExample.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ByteArrayTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ObjectTypeVisitor.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_ApplicationJson_ArrayObject_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_ApplicationJson_ArrayObject_HttpTrigger.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/ArrayObjectModel.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/Int32ObjectModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/ByteArrayTypeVisitorTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/ListObjectTypeVisitorTests.cs
Labels: enhancement, v0.9.0

#218 fixed that fails to use a model with a property named Aliases
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/DictionaryObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ListObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ObjectTypeVisitor.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_ApplicationJson_ArrayObject_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_ApplicationJson_DictionaryObject_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_ApplicationJson_DictionaryObject_HttpTrigger.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/ArrayObjectModel.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/DictionaryObjectModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeAliasCollectionModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeAliasDictionaryModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeAliasSubModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeDummyModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/DictionaryObjectTypeVisitorTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/ListObjectTypeVisitorTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/ObjectTypeVisitorTests.cs
Labels: bug, v0.9.0, oca-pr, oca-issue

#233 Feature/#156 list of recursive models
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/DummyResponseModel.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/DictionaryObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ListObjectTypeVisitor.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_ApplicationJson_GenericAndRecursive_HttpTrigger.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/GenericAndRecursiveModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeClassModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/DocumentHelperTests.cs
Labels: bug, v0.9.0

#236 Add integration testing for Boolean Object Type (#143)
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Post_ApplicationJson_Boolean_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/BooleanObjectModel.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Post_ApplicationJson_Boolean_HttpTrigger.cs
Labels: enhancement, oca-pr

#234 Support "Base Object (root of all classes)" type
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/BaseObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ObjectTypeVisitor.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_ApplicationJson_BaseObject_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_ApplicationJson_BaseObject_HttpTrigger.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/HasBaseObjectModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/BaseObjectTypeVisitorTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/ObjectTypeVisitorTests.cs
Labels: enhancement, v0.9.0, oca-pr, oca-issue

#242 Fix: Change links to moved docs
  docs/enable-open-api-endpoints.md
  docs/openapi.md
Labels: documentation

#239 Add DoubleObject to test-integration (#143)
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Post_ApplicationJson_Double_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Models/DoubleObjectModel.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Post_ApplicationJson_Double_HttpTrigger.cs
Labels: enhancement, oca-pr, oca-issue

#247 Update type extension methods to detect broader range of arrays and dictionaries
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/TypeExtensionsTests.cs
Labels: bug, v0.9.0
