Repository Azure/azure-functions-openapi-extension, pull requests merged in 2022-08, with the labels that each got.

#435 Support dynamic `OpenApiHttpTriggerAuthorization`
  docs/openapi-core.md
  docs/openapi-in-proc.md
  docs/openapi-out-of-proc.md
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Configurations/MyOpenApiHttpTriggerAuthorization.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Program.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Configurations/MyOpenApiHttpTriggerAuthorization.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Configurations/OpenApiHttpTriggerAuthorization.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Startup.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Extensions/OpenApiHostBuilderExtensions.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiHttpTriggerAuthorizationIgnoreAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiHttpTriggerAuthorization.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/OpenApiHttpTriggerAuthorizationResolver.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeOpenApiHttpTriggerAuthorization.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Resolvers/OpenApiHttpTriggerAuthorizationResolverTests.cs
Labels: v1.4.0

#476 Add delegate OpenApiHttpTriggerAuthorization to be more configurable
  docs/openapi-core.md
  docs/openapi-in-proc.md
  docs/openapi-out-of-proc.md
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Configurations/MyOpenApiHttpTriggerAuthorization.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Program.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Configurations/MyOpenApiHttpTriggerAuthorization.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Startup.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Extensions/OpenApiHostBuilderExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiHttpTriggerAuthorizationIgnoreAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiHttpTriggerAuthorization.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiHttpTriggerAuthorization.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/OpenApiConfigurationResolver.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/OpenApiHttpTriggerAuthorizationResolver.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeOpenApiConfigurationOptionsBase.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeOpenApiHttpTriggerAuthorization.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/OpenApiHttpTriggerAuthorizationTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/TypeExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Resolvers/OpenApiHttpTriggerAuthorizationResolverTests.cs
Labels: enhancement, v1.4.0

#477 V2/ Merge `OpenApiHttpTriggerAuthorization` with `OpenApiConfigurationOptions`
  .github/workflows/main-build.yaml
  builds/build-dev.yaml
  docs/openapi-in-proc.md
  docs/openapi-out-of-proc.md
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Program.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Startup.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/DefaultOpenApiConfigurationOptionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/OpenApiConfigurationOptionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
Labels: documentation, enhancement, v2.0.0

#483 Make `OpenApiCustomUIOptions` Injectable
  docs/openapi-core.md
  docs/openapi-in-proc.md
  docs/openapi-out-of-proc.md
  docs/openapi.md
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Configurations/MyOpenApiCustomUIOptions.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.csproj
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Program.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/dist/my-custom.css
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/dist/my-custom.js
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Configurations/MyOpenApiCustomUIOptions.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Configurations/OpenApiCustomUIOptions.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Startup.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/dist/my-custom.js
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiCustomUIOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiCustomUIOptionsIgnoreAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiCustomUIOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiCustomUIOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/OpenApiCustomUIResolver.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeFileCustomUIOptions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeUriCustomUIOptions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/OpenApiCustomUIOptionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Resolvers/OpenApiCustomUIResolverTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiHttpTriggerContextTests.cs
Labels: documentation, enhancement, v1.5.0
