Repository Azure/azure-functions-openapi-extension, pull requests merged in 2022-12, with the labels that each got.

#522 .NET 7 support for out-of-process worker
  .github/workflows/main-actions.yaml
  .github/workflows/main-build.yaml
  .github/workflows/pr.yaml
  Microsoft.Azure.WebJobs.Extensions.OpenApi.sln
  builds/template-steps-build-test.yaml
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.Ping/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.Ping.csproj
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc.csproj
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Extensions/OpenApiHttpRequestDataExtensions.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/.npmignore
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/.vscode/launch.json
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/.vscode/tasks.json
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/Program.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/ProjectInfo.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/lib/copy-metadata.js
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/lib/install.js
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/lib/main.js
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/package.json
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Microsoft.Azure.WebJobs.Extensions.OpenApi.csproj
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests.csproj
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp.csproj
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests/ProjectInfoTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests.csproj
Labels: enhancement, v1.5.0

#523 Add implicit DI feature for out-of-proc worker
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Program.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/OpenApiWorkerStartup.cs
Labels: enhancement, v1.5.0

#526 Update OpenApiSettings
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.Ping/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.Ping.csproj
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.Ping/PingHttpTrigger.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/PetHttpTrigger.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/StoreHttpTrigger.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/UserHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/PetHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/StoreHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/UserHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/host.json
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Configurations/OpenApiAuthLevelSettings.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/OpenApiWorkerStartup.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/HttpBindingMetadata.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IHttpRequestDataObject.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiAuthLevelSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Configurations/OpenApiAuthLevelSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctionProvider.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiWebJobsStartup.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/OpenApiWorkerStartupTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/OpenApiAuthLevelSettingsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/OpenApiSettingsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/Configurations/OpenApiSettingsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiTriggerFunctionProviderTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiWebJobsStartupTests.cs
Labels: enhancement, v2.0.0-preview1

#528 Update sample app that applies v1.5.0
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.Ping/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.Ping.csproj
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.csproj
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/PetHttpTrigger.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/StoreHttpTrigger.cs
  samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/UserHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/PetHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/StoreHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/UserHttpTrigger.cs
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/host.json
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models.csproj
Labels: documentation

#524 add TimeSpanObjectTypeVisitor
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/EnumExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/RecursiveObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/TimeSpanObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/TypeVisitor.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeTimeSpanParameterExample.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Abstractions/OpenApiExampleTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/EnumExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/TypeExtensionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/TimeSpanObjectTypeVisitorTests.cs
Labels: bug, v1.6.0
