Repository Azure/azure-functions-openapi-extension, pull requests merged in 2022-10, with the labels that each got.

#497 Add devcontainer settings
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-create.sh
Labels: v1.5.0

#498 Add OpenAPI document generation scripts - `.ps1` and `.sh`
  README.md
  actions/Get-OpenApiDocument.ps1
  actions/get-openapi-document.sh
Labels: enhancement, v1.5.0

#494 Fix typo from Wroker to Worker
  README.md
Labels: documentation, v1.5.0

#493 Upgrade version of Microsoft.Azure.WebJobs.Extensions.Http to remove vulnerability
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.csproj
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests.csproj
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes.csproj
Labels: enhancement, v1.5.0
