Repository Azure/azure-functions-openapi-extension, pull requests merged in 2022-02, with the labels that each got.

#330 Allow relative URL being used as base URL
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs
Labels: enhancement, v1.1.0

#301 Fix: OpenAPI attributes are not getting picked up if they are in a referenced class library project #298
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Extensions/DocumentHelperExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/AssemblyExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/VisitorCollection.cs
Labels: bug, v1.1.0

#297 Add a HideDocument flag akin to HideSwaggerUI
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctionProvider.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/Configurations/OpenApiSettingsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/OpenApiTriggerFunctionProviderTests.cs
Labels: enhancement, hacktoberfest, v1.1.0

#329 Deprecated feature implementation #319
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Attributes/OpenApiPropertyAttribute.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/Int16EnumTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/Int32EnumTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/Int64EnumTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/NullableObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/StringEnumTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/TypeVisitor.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Attributes/OpenApiPropertyAttributeTests.cs
Labels: documentation, enhancement, v1.1.0

#364 Fix RecursiveObjectTypeVisitor to filter duplicated field names
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ObjectTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/RecursiveObjectTypeVisitor.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeRecursiveModel.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/ObjectTypeVisitorTests.cs
Labels: bug, v1.2.0

#367 multipart/form-data in OpenAPI v2 Rendering Workaround (Interim)
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Startup.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/DocumentHelperExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/ByteArrayTypeVisitor.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Post_ApplicationJson_ByteArrayObject_Tests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Visitors/ByteArrayTypeVisitorTests.cs
Labels: bug, enhancement, v1.2.0

#368 Update logic for isolated worker
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Document.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Extensions/DocumentHelperExtensions.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/DocumentHelper.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/DocumentHelperExtensions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.csproj
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Microsoft.Azure.WebJobs.Extensions.OpenApi.csproj
Labels: bug, enhancement, v1.2.0

#362 Do not consider abstract classes in configuration options
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Resolvers/OpenApiConfigurationResolver.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeOpenApiConfigurationOptions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.Fakes/FakeOpenApiConfigurationOptionsBase.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Resolvers/OpenApiConfigurationResolverTests.cs
Labels: enhancement, v1.2.0
