Repository Azure/azure-functions-openapi-extension, pull requests merged in 2022-03, with the labels that each got.

#344 Allow IDocument to be modified before rendering
  docs/openapi.md
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Filters/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Filters.csproj
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc.csproj
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Document.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Functions/OpenApiTriggerFunction.cs
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IDocument.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IDocumentFilter.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Filters/DocumentFilterCollection.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctions.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Get_DocumentFilter_Tests.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Configurations/OpenApiConfigurationOptions.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/DocumentFilters/RewriteDescriptionDocumentFilter.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Get_DocumentFilter_HttpTrigger.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/DocumentTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/DocumentTests.cs
Labels: documentation, enhancement, v1.3.0

#392 Update properties to be virtual on DefaultOpenApiConfigurationOptions
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiConfigurationOptions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/DefaultOpenApiConfigurationOptionsTests.cs
Labels: documentation, enhancement, v1.3.0

#381 Ignore failure during assembly loading
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/AssemblyExtensions.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Extensions/AssemblyExtensionsTests.cs
Labels: bug, v1.3.0

#395 Update GetTypesFromReferencedFunctionApps
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/AssemblyExtensions.cs
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Tests.csproj
  test-integration/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp/Microsoft.Azure.WebJobs.Extensions.OpenApi.TestApp.csproj
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.AppSettings.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests.csproj
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests.csproj
Labels: bug, v1.3.0

#383 Fix: Funktion key from config gets overwritten by function key in url
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/SwaggerUITests.cs
Labels: bug, v1.3.0

#397 Change IncludeRequestingHostName to ExcludeRequestingHost
  docs/openapi-core.md
  docs/openapi.md
  samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Filters/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Filters.csproj
  src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Document.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiConfigurationOptions.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/OpenApiSettings.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs
  src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs
  test/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Tests/DocumentTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/Configurations/DefaultOpenApiConfigurationOptionsTests.cs
  test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Tests/DocumentTests.cs
Labels: documentation, enhancement, v2.0.0
